//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsTransactionVoucherDetail
    {
        public int Id { get; set; }
        public int VoucherId { get; set; }
        public int AccountId { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string CheckTitle { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChcequeDate { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<bool> IsCredit { get; set; }
    }
}
