//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsTransactionVoucherHead
    {
        public int Id { get; set; }
        public int VoucherTypeId { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string VoucherNumber { get; set; }
        public string VoucherMethod { get; set; }
        public Nullable<int> ReferenceAccountId { get; set; }
        public string VoucherRemarks { get; set; }
        public string VoucherStatus { get; set; }
        public Nullable<int> EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> PostedUserId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    }
}
