//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactionSaleHead
    {
        public int Id { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string SaleNo { get; set; }
        public int CustomerId { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> SaleTotalAmount { get; set; }
        public Nullable<int> SaleOrderId { get; set; }
        public string SaleStatus { get; set; }
        public Nullable<int> EntryUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> PostedUserId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    }
}
