//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> PackQuantity { get; set; }
        public Nullable<decimal> UnitPurchasePrice { get; set; }
        public Nullable<decimal> UnitSalePrice { get; set; }
        public Nullable<bool> IsVat { get; set; }
        public Nullable<double> StockMaxLevel { get; set; }
        public Nullable<double> StoctNormalLevel { get; set; }
        public Nullable<double> StockMinLevel { get; set; }
        public string ItemImagePath { get; set; }
        public int ItemUnitId { get; set; }
        public int ItemGroupId { get; set; }
        public int ItemCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
