//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactionPurchaseHead
    {
        public int Id { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string PurchaseNo { get; set; }
        public int VendorId { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> PurchaseTotalAmount { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public string PurchaseStatus { get; set; }
        public Nullable<int> EntryUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> PostedUserId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    }
}
